on: [push]

env:
  VERSION: 0.0.1-develop.exp.sha.${GITHUB_SHA::6}
jobs:
  vars: 
    # setup vars for easier usage (eg. needs.vars.outputs.DOCKER_IMAGE_TAG ); 
    # useful when building vars based on env
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.docker.outputs.VERSION }}
    steps:
      - id: docker
        run: echo "::set-output name=VERSION::some.random.string.${{ env.VERSION }}"
      - id: helm
        run: echo "${{env.VERSION}}"

  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    needs: [vars]
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: ./.github/actions/testcomposite
        name: testinglocal
      - name: failure
        run: echo "${{ needs.vars.outputs.VERSION }}"
      - name: failure
        run: echo "${{ env.VERSION }}"
      - name: failure
        run: "${{ needs.vars.outputs.VERSION }}"
      - name: failure
        run: "${{ env.VERSION }}"
      - name: failure
        run: helm uninstall app
      - name: should run
        if: always()
        run: echo "running"
      - name: should run 2
        run: echo "running 2"
