on: [push]

env:
  TEST: 0.0.0-test.${{ github.sha::6 }}
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: ./.github/actions/testcomposite
        name: testinglocal
      - name: failure
        run: echo "${{ env.TEST }}"
      - name: failure
        run: helm uninstall app
      - name: should run
        if: always()
        run: echo "running"
      - name: should run 2
        run: echo "running 2"
